version: '3.7'
services:
  ala-microservice-nginx:
    build: ./docker/dev/nginx
    container_name: ala-microservice-nginx
    depends_on:
      - ala-microservice-php
    ports:
      - 8101:80
    volumes:
      - ./:/var/www/html

  ala-microservice-php:
    build: ./docker/dev/php-clear
    container_name: ala-microservice-php
    volumes:
      - ./:/var/www/html

  ala-microservice-mysql:
    image: mysql:8.0.23
    container_name: ala-microservice-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=ala
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql-db:/docker-entrypoint-initdb.d
      - ./storage/.db:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
